### ISSUE TITLE
 jmp-0.0.2.tar.gz on PyPY doesn't contain requirements.txt

### ISSUE THREAD

**Issue by ostueker** [deepmind/jmp#19]
When trying to build my own wheel from the tar-ball of jmp-0.0.2 that has been uploaded to PyPI I get the following error:

```
Collecting jmp==0.0.2
  Downloading jmp-0.0.2.tar.gz (13 kB)
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-zowwz99o/jmp_55ae4a2c4cdb44aa99c65fbf7a5ee9bb/setup.py", line 55, in <module>
        install_requires=_parse_requirements('requirements.txt'),
      File "/tmp/pip-download-zowwz99o/jmp_55ae4a2c4cdb44aa99c65fbf7a5ee9bb/setup.py", line 32, in _parse_requirements
        with open(requirements_txt_path) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: Discarding https://files.pythonhosted.org/packages/7c/ba/a6bfcaeedca8551e2fb4054d1fd061a0dd97d26dd44002b3e92d13b51877/jmp-0.0.2.tar.gz#sha256=fdb5cec0d10aab4116c2770f24b2adf4f503fcfbb96ce8ef583e1879bdbf1b9b (from https://pypi.org/simple/jmp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement jmp==0.0.2 (from versions: 0.0.1, 0.0.2)
ERROR: No matching distribution found for jmp==0.0.2
```

After downloading and extracting `jmp-0.0.2.tar.gz` [from PyPI](https://pypi.org/project/jmp/#files) and looking at `setup.py`, I see that it contains lines that reference requirements.txt:
```python
install_requires=_parse_requirements('requirements.txt')
```
however that file is not part of the source distribution and my build fails.

Oliver

P.S. Yes I know that there is a wheel for jmp-0.0.2 on PyPI, which I ended up using, but I'm using our [Wheels_builder](https://github.com/ComputeCanada/wheels_builder) script that will recursively build wheels for dependencies for our systems.
My point is that the source distribution of jmp 0.0.2 is incomplete as it lacks the information that is contained in the requirements file.

**Comment by tomhennigan** [comment]
Thank you for the report, this will be fixed in the next release of jmp.
